# Generated by Django 4.2 on 2023-05-23 12:49

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_reply_image_alter_tweetimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.reply_image_store),
        ),
    ]
